#!/usr/bin/ruby

require_relative 'health_log'


file = File.join __dir__, 'history.yml'
log = HealthLog.new file

puts
puts "Record a health log entry!"
puts "Valid tokens: #{log.tokens.join(', ')}"
puts

input = gets.chomp

log.entry input
puts

def normalize(text)
  text.to_s
end

def justify(string)
  (normalize(string) + ':').ljust 15
end

log.last_n_days(7).each do |date, data|
  puts; puts date
  log.tokens.each do |token|
    field = log.send(:keyword_mapping)[token]
    value = data[field.to_sym]
    puts ['   ', justify(field), value].join
  end
end

puts
