# You can edit these tokens as desired. Put them in the order you'd like them displayed
---
tokens:
  w: 'weight'
  s: 'sleep'
  x: 'exercise'
  bl: 'belt loop'
  bl: 'belt loop'
  c: 'comments'
  dq: 'diet quality'
  dv: 'diet volume'
